arb-dir: assets/locales
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/core/localizations
synthetic-package: false
untranslated-messages-file: untranslated.txt