name: my_articles_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  loader_overlay: ^4.0.0
  pretty_dio_logger: ^1.3.1
  responsive_sizer: ^3.3.0+1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  translator: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/locales/

fonts:
  - family: Inter
    fonts:
      - asset: assets/font/Inter-Regular.ttf
