name: my_articles_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  loader_overlay: ^2.3.2
  pretty_dio_logger: ^1.3.1
  responsive_sizer: ^3.2.0
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  translator: ^0.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/locales/

fonts:
  - family: Inter
    fonts:
      - asset: assets/font/Inter-Regular.ttf
